// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyunL8Mg4QDR4OQvom2k8e5-DnGJv5Ouw',
    appId: '1:815076675923:web:d8b160826e19c9c25f51a6',
    messagingSenderId: '815076675923',
    projectId: 'taxi-buddy-874a2',
    authDomain: 'taxi-buddy-874a2.firebaseapp.com',
    storageBucket: 'taxi-buddy-874a2.appspot.com',
    measurementId: 'G-LS4NJ1W81M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ-VDIbJ1q0fDIIUsOIOUA7_M4F_l9LHc',
    appId: '1:815076675923:android:c2da86fd19783c025f51a6',
    messagingSenderId: '815076675923',
    projectId: 'taxi-buddy-874a2',
    storageBucket: 'taxi-buddy-874a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUykz_WyS8hlGIa707x6LlP6kCtsh8feo',
    appId: '1:815076675923:ios:823c6e6a5bd7bd395f51a6',
    messagingSenderId: '815076675923',
    projectId: 'taxi-buddy-874a2',
    storageBucket: 'taxi-buddy-874a2.appspot.com',
    androidClientId: '815076675923-8cu8s9agnh04f7rr443dvqqrpkh20645.apps.googleusercontent.com',
    iosClientId: '815076675923-3cru77l9rjp3f1qejt0odifg91uhth4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUykz_WyS8hlGIa707x6LlP6kCtsh8feo',
    appId: '1:815076675923:ios:36e87e21f743b2c35f51a6',
    messagingSenderId: '815076675923',
    projectId: 'taxi-buddy-874a2',
    storageBucket: 'taxi-buddy-874a2.appspot.com',
    androidClientId: '815076675923-8cu8s9agnh04f7rr443dvqqrpkh20645.apps.googleusercontent.com',
    iosClientId: '815076675923-0fjo5vqfjie7r6m6vql0vr9r85i98mer.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
